// Code generated by tron v0.19.2. DO NOT EDIT.
package config

const (
	DbHost                = "db_host"
	DbName                = "db_name"
	DbPassword            = "db_password"
	DbPort                = "db_port"
	DbUser                = "db_user"
	ExampleValue          = "example_value"
	FileCacheDir          = "file_cache_dir"
	JaegerSamplerParam    = "jaeger_sampler_param"
	JaegerSamplerType     = "jaeger_sampler_type"
	MemoryCacheLifeWindow = "memory_cache_life_window"
	MemoryCacheMaxSize    = "memory_cache_max_size"
	RendererQueueCapacity = "renderer_queue_capacity"
	RendererWorkersCount  = "renderer_workers_count"
)
